# Generated by Django 5.1.4 on 2024-12-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortCode', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
