# Generated by Django 5.1.4 on 2024-12-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
